export const YOUTUBE_NICHES = [
  'Technologie',
  'Intelligence artificielle',
  'Business',
  'Marketing',
  'Finance',
  'Immobilier',
  'E-commerce',
  'Entrepreneuriat',
  'Productivité',
  'Éducation',
  'Développement personnel',
  'Sport',
  'Fitness',
  'Santé et bien-être',
  'Mode',
  'Beauté',
  'Voyage',
  'Cuisine',
  'Gaming',
  'Automobile',
  'Musique',
  'Cinéma et séries',
  'Divertissement',
  'Actualité et société',
  'Science',
  'Développement informatique',
  'Photographie et vidéo',
  'Famille et parentalité',
] as const

export const YOUTUBE_NICHE_QUERIES: Record<string, string> = {
  Technologie: 'tech nouvelles technologies gadgets',
  'Intelligence artificielle': 'intelligence artificielle IA outils',
  Business: 'business entrepreneur entreprise',
  Marketing: 'marketing digital growth acquisition',
  Finance: 'finance investissement argent',
  Immobilier: 'immobilier investissement locatif',
  'E-commerce': 'ecommerce shopify vente en ligne',
  Entrepreneuriat: 'entrepreneur startup business',
  Productivité: 'productivité organisation outils',
  Éducation: 'education tutoriel formation',
  'Développement personnel': 'développement personnel mindset',
  Sport: 'sport entraînement performance',
  Fitness: 'fitness musculation workout',
  'Santé et bien-être': 'santé bien-être nutrition',
  Mode: 'mode fashion style',
  Beauté: 'beauté skincare maquillage',
  Voyage: 'travel voyage vlog',
  Cuisine: 'cooking recette cuisine',
  Gaming: 'gaming gameplay streamer',
  Automobile: 'automobile voitures essais',
  Musique: 'music artiste musicien',
  'Cinéma et séries': 'cinema séries films',
  Divertissement: 'divertissement humour entertainment',
  'Actualité et société': 'actualité société débats',
  Science: 'science vulgarisation sciences',
  'Développement informatique': 'développement informatique programmation coding',
  'Photographie et vidéo': 'photographie vidéo camera montage',
  'Famille et parentalité': 'famille parentalité parents',
  'Finance & Business': 'finance business investing entrepreneur',
  'Tech & Programmation': 'tech programming coding',
  'Fitness & Santé': 'fitness health workout',
  'Lifestyle & Vlog': 'lifestyle vlog',
  'Beauté & Mode': 'beauty fashion',
}

export const SMALL_CREATOR_NICHE_QUERIES: Record<string, string[]> = {
  Technologie: ['tech français', 'nouvelle chaîne tech', 'test gadget français'],
  'Intelligence artificielle': ['outils IA français', 'intelligence artificielle français'],
  Business: ['business français', 'entrepreneur français', 'startup français'],
  Marketing: ['marketing digital français', 'growth marketing français'],
  Finance: ['investissement débutant', 'finance personnelle français'],
  Immobilier: ['immobilier français', 'investissement locatif français'],
  'E-commerce': ['shopify français', 'ecommerce français'],
  Entrepreneuriat: ['entrepreneur français', 'créateur business français'],
  Productivité: ['organisation productivité français', 'notion productivité français'],
  Éducation: ['tutoriel français', 'formation français'],
  'Développement personnel': ['développement personnel français', 'mindset français'],
  Sport: ['sport français', 'entraînement français'],
  Fitness: ['fitness français', 'musculation français', 'coach sportif français'],
  'Santé et bien-être': ['bien-être français', 'nutrition française'],
  Mode: ['mode française', 'style français'],
  Beauté: ['beauté française', 'skincare français'],
  Voyage: ['vlog voyage français', 'voyage français'],
  Cuisine: ['recette française', 'cuisine maison'],
  Gaming: ['petit youtubeur', 'gaming fr', 'gameplay fr', 'streamer fr', 'nouvelle chaîne gaming'],
  Automobile: ['essai voiture français', 'automobile français'],
  Musique: ['musicien français', 'beatmaker français'],
  'Cinéma et séries': ['cinéma français', 'critique séries français'],
  Divertissement: ['humour français', 'divertissement français'],
  'Actualité et société': ['actualité française', 'société français'],
  Science: ['vulgarisation science français', 'science français'],
  'Développement informatique': ['développeur français', 'programmation français', 'coding français'],
  'Photographie et vidéo': ['photographie français', 'montage vidéo français'],
  'Famille et parentalité': ['parentalité français', 'famille française'],
  'Finance & Business': ['investissement débutant', 'business français', 'entrepreneur français'],
  'Tech & Programmation': ['développeur français', 'programmation français', 'coding français'],
  'Fitness & Santé': ['fitness français', 'musculation français', 'coach sportif français'],
  'Lifestyle & Vlog': ['vlog français', 'lifestyle français'],
  'Beauté & Mode': ['mode française', 'beauté française'],
}
